bookings:
- dropoff_date: '2026-07-26'
  dropoff_time: '22:00'
  holding_price: 376.58
  holding_vehicle_type: Fullsize Car
  name: hawaii_july
  pickup_date: '2026-07-22'
  pickup_location: HNL
  pickup_time: 09:00
database:
  path: data/results.db
imessage:
  phone_number: '+15039990921'
