search:
  pickup_location: SAN
  pickup_date: '2026-04-02'
  pickup_time: '10:00'
  dropoff_date: '2026-04-08'
  dropoff_time: '10:00'
  holding_price: 375.23
  holding_vehicle_type: Standard Car
database:
  path: data/results.db
imessage:
  phone_number: '+15039990921'
